server:
  port: 8888

deploy:
#  url: http://139.196.75.247:8888
  url: http://localhost:8888

spring:
  datasource:
    name: test
    url: jdbc:mysql://139.196.75.247:3306/smt?characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    username: smt
    password: smt2018
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.163.com
    username: smt_group@163.com
    password: smt2019
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

logging:
  config: classpath:logback.xml

  #mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.smtteam.smt.model

