server:
  port: 8888

spring:
  datasource:
    name: test
    url: jdbc:mysql://139.196.75.247:3306/smt?characterEncoding=UTF-8&amp;characterSetResults=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.smtteam.smt.model
